//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPresentationFoundation.SmartCityReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonneWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    [System.SerializableAttribute()]
    public partial class PersonneWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DIJointureWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    [System.SerializableAttribute()]
    public partial class DIJointureWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDefautField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsPresentationFoundation.SmartCityReference.Binary PhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentaire {
            get {
                return this.CommentaireField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentaireField, value) != true)) {
                    this.CommentaireField = value;
                    this.RaisePropertyChanged("Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etat {
            get {
                return this.EtatField;
            }
            set {
                if ((object.ReferenceEquals(this.EtatField, value) != true)) {
                    this.EtatField = value;
                    this.RaisePropertyChanged("Etat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDefaut {
            get {
                return this.IdDefautField;
            }
            set {
                if ((this.IdDefautField.Equals(value) != true)) {
                    this.IdDefautField = value;
                    this.RaisePropertyChanged("IdDefaut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsPresentationFoundation.SmartCityReference.Binary Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefautWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    [System.SerializableAttribute()]
    public partial class DefautWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDefautField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDefautField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsPresentationFoundation.SmartCityReference.Binary PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDefaut {
            get {
                return this.DateDefautField;
            }
            set {
                if ((this.DateDefautField.Equals(value) != true)) {
                    this.DateDefautField = value;
                    this.RaisePropertyChanged("DateDefaut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDefaut {
            get {
                return this.IdDefautField;
            }
            set {
                if ((this.IdDefautField.Equals(value) != true)) {
                    this.IdDefautField = value;
                    this.RaisePropertyChanged("IdDefaut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsPresentationFoundation.SmartCityReference.Binary Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterventionWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    [System.SerializableAttribute()]
    public partial class InterventionWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateInterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefautField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInterventionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentaire {
            get {
                return this.CommentaireField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentaireField, value) != true)) {
                    this.CommentaireField = value;
                    this.RaisePropertyChanged("Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIntervention {
            get {
                return this.DateInterventionField;
            }
            set {
                if ((this.DateInterventionField.Equals(value) != true)) {
                    this.DateInterventionField = value;
                    this.RaisePropertyChanged("DateIntervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Defaut {
            get {
                return this.DefautField;
            }
            set {
                if ((this.DefautField.Equals(value) != true)) {
                    this.DefautField = value;
                    this.RaisePropertyChanged("Defaut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etat {
            get {
                return this.EtatField;
            }
            set {
                if ((object.ReferenceEquals(this.EtatField, value) != true)) {
                    this.EtatField = value;
                    this.RaisePropertyChanged("Etat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIntervention {
            get {
                return this.IdInterventionField;
            }
            set {
                if ((this.IdInterventionField.Equals(value) != true)) {
                    this.IdInterventionField = value;
                    this.RaisePropertyChanged("IdIntervention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Personne {
            get {
                return this.PersonneField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonneField, value) != true)) {
                    this.PersonneField = value;
                    this.RaisePropertyChanged("Personne");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmartCityReference.IServiceWCFSmartCity")]
    public interface IServiceWCFSmartCity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/Connexion", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/ConnexionResponse")]
        WindowsPresentationFoundation.SmartCityReference.PersonneWCF Connexion(string m, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/Connexion", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/ConnexionResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.PersonneWCF> ConnexionAsync(string m, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventions", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsResponse")]
        WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[] GetDefautsInterventions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventions", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[]> GetDefautsInterventionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsByMail", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsByMailResponse")]
        WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[] GetDefautsInterventionsByMail(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsByMail", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautsInterventionsByMailResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[]> GetDefautsInterventionsByMailAsync(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllDefauts", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllDefautsResponse")]
        WindowsPresentationFoundation.SmartCityReference.DefautWCF[] GetAllDefauts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllDefauts", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllDefautsResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DefautWCF[]> GetAllDefautsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautById", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautByIdResponse")]
        WindowsPresentationFoundation.SmartCityReference.DefautWCF GetDefautById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautById", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautByIdResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DefautWCF> GetDefautByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDate", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDateRespon" +
            "se")]
        WindowsPresentationFoundation.SmartCityReference.InterventionWCF[] GetInterventionsByDefautOrderByDate(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDate", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDateRespon" +
            "se")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.InterventionWCF[]> GetInterventionsByDefautOrderByDateAsync(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefaut", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefautResponse")]
        WindowsPresentationFoundation.SmartCityReference.InterventionWCF GetLastInterventionByDefaut(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefaut", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefautResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.InterventionWCF> GetLastInterventionByDefautAsync(int d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/AddIntervention", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/AddInterventionResponse")]
        void AddIntervention(string e, string c, System.DateTime d, int def, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/AddIntervention", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/AddInterventionResponse")]
        System.Threading.Tasks.Task AddInterventionAsync(string e, string c, System.DateTime d, int def, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriers", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriersResponse")]
        WindowsPresentationFoundation.SmartCityReference.PersonneWCF[] GetAllOuvriers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriers", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriersResponse")]
        System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.PersonneWCF[]> GetAllOuvriersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFSmartCityChannel : WindowsPresentationFoundation.SmartCityReference.IServiceWCFSmartCity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFSmartCityClient : System.ServiceModel.ClientBase<WindowsPresentationFoundation.SmartCityReference.IServiceWCFSmartCity>, WindowsPresentationFoundation.SmartCityReference.IServiceWCFSmartCity {
        
        public ServiceWCFSmartCityClient() {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartCityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsPresentationFoundation.SmartCityReference.PersonneWCF Connexion(string m, string pwd) {
            return base.Channel.Connexion(m, pwd);
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.PersonneWCF> ConnexionAsync(string m, string pwd) {
            return base.Channel.ConnexionAsync(m, pwd);
        }
        
        public WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[] GetDefautsInterventions() {
            return base.Channel.GetDefautsInterventions();
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[]> GetDefautsInterventionsAsync() {
            return base.Channel.GetDefautsInterventionsAsync();
        }
        
        public WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[] GetDefautsInterventionsByMail(string m) {
            return base.Channel.GetDefautsInterventionsByMail(m);
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DIJointureWCF[]> GetDefautsInterventionsByMailAsync(string m) {
            return base.Channel.GetDefautsInterventionsByMailAsync(m);
        }
        
        public WindowsPresentationFoundation.SmartCityReference.DefautWCF[] GetAllDefauts() {
            return base.Channel.GetAllDefauts();
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DefautWCF[]> GetAllDefautsAsync() {
            return base.Channel.GetAllDefautsAsync();
        }
        
        public WindowsPresentationFoundation.SmartCityReference.DefautWCF GetDefautById(int id) {
            return base.Channel.GetDefautById(id);
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.DefautWCF> GetDefautByIdAsync(int id) {
            return base.Channel.GetDefautByIdAsync(id);
        }
        
        public WindowsPresentationFoundation.SmartCityReference.InterventionWCF[] GetInterventionsByDefautOrderByDate(int d) {
            return base.Channel.GetInterventionsByDefautOrderByDate(d);
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.InterventionWCF[]> GetInterventionsByDefautOrderByDateAsync(int d) {
            return base.Channel.GetInterventionsByDefautOrderByDateAsync(d);
        }
        
        public WindowsPresentationFoundation.SmartCityReference.InterventionWCF GetLastInterventionByDefaut(int d) {
            return base.Channel.GetLastInterventionByDefaut(d);
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.InterventionWCF> GetLastInterventionByDefautAsync(int d) {
            return base.Channel.GetLastInterventionByDefautAsync(d);
        }
        
        public void AddIntervention(string e, string c, System.DateTime d, int def, string p) {
            base.Channel.AddIntervention(e, c, d, def, p);
        }
        
        public System.Threading.Tasks.Task AddInterventionAsync(string e, string c, System.DateTime d, int def, string p) {
            return base.Channel.AddInterventionAsync(e, c, d, def, p);
        }
        
        public WindowsPresentationFoundation.SmartCityReference.PersonneWCF[] GetAllOuvriers() {
            return base.Channel.GetAllOuvriers();
        }
        
        public System.Threading.Tasks.Task<WindowsPresentationFoundation.SmartCityReference.PersonneWCF[]> GetAllOuvriersAsync() {
            return base.Channel.GetAllOuvriersAsync();
        }
    }
}
