<?xml version="1.0" encoding="utf-8"?><Database Name="SmartCity" Class="DataContextDALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=UTILISATEUR-PC\SQLEXPRESS;Initial Catalog=SmartCity;Integrated Security=True" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="SmartCityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEFAUTS" Member="DEFAUTs">
    <Type Name="DEFAUT">
      <Column Name="IdDefaut" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="DEFAUT_INTERVENTION" Member="INTERVENTIONs" ThisKey="IdDefaut" OtherKey="Defaut" Type="INTERVENTION" />
    </Type>
  </Table>
  <Table Name="dbo.INTERVENTIONS" Member="INTERVENTIONs">
    <Type Name="INTERVENTION">
      <Column Name="IdIntervention" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Etat" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Commentaire" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DateIntervention" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Defaut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Personne" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DEFAUT_INTERVENTION" Member="DEFAUT1" ThisKey="Defaut" OtherKey="IdDefaut" Type="DEFAUT" IsForeignKey="true" />
      <Association Name="PERSONNE_INTERVENTION" Member="PERSONNE1" ThisKey="Personne" OtherKey="Mail" Type="PERSONNE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERSONNES" Member="PERSONNEs">
    <Type Name="PERSONNE">
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="PERSONNE_INTERVENTION" Member="INTERVENTIONs" ThisKey="Mail" OtherKey="Personne" Type="INTERVENTION" />
    </Type>
  </Table>
</Database>