<?xml version="1.0" encoding="utf-8"?><Database Name="SmartCity" Class="DataContextDALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=UTILISATEUR-PC\SQLEXPRESS;Initial Catalog=SmartCity;Integrated Security=True" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="SmartCityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Defauts" Member="Defauts">
    <Type Name="Defaut">
      <Column Name="IdDefaut" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="Defaut_Intervention" Member="Interventions" ThisKey="IdDefaut" OtherKey="Defaut" Type="Intervention" />
    </Type>
  </Table>
  <Table Name="dbo.Personnes" Member="Personnes">
    <Type Name="Personne">
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Personne_Intervention" Member="Interventions" ThisKey="Mail" OtherKey="Personne" Type="Intervention" />
    </Type>
  </Table>
  <Table Name="dbo.Interventions" Member="Interventions">
    <Type Name="Intervention">
      <Column Name="IdIntervention" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Etat" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Commentaire" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DateIntervention" Type="System.DateTime" DbType="Date" CanBeNull="false" />
      <Column Name="Defaut" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="Personne" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Defaut_Intervention" Member="Defaut1" ThisKey="Defaut" OtherKey="IdDefaut" Type="Defaut" IsForeignKey="true" />
      <Association Name="Personne_Intervention" Member="Personne1" ThisKey="Personne" OtherKey="Mail" Type="Personne" IsForeignKey="true" />
    </Type>
  </Table>
</Database>