BEGIN
	INSERT INTO DEFAUTS (PHOTO, DESCRIPTION, POSITION) VALUES (NULL, 'Nid de poule à Verviers',NULL);

	INSERT INTO PERSONNES (MAIL, PASSWORD, NOM, PRENOM, TYPE) VALUES ('oceane.seel@hotmail.com', 'oce', 'SEEL', 'Océane', 'CHEF');
	INSERT INTO PERSONNES (MAIL, PASSWORD, NOM, PRENOM, TYPE) VALUES ('jerome.fink@hotmail.com', 'je', 'FINK', 'Jérôme', 'OUVRIER');

	INSERT INTO INTERVENTIONS (ETAT, COMMENTAIRE, DATEINTERVENTION, DEFAUT, PERSONNE) VALUES('OUVERT', 'Problème ouvert', '2015-11-17', 1, 'oceane.seel@hotmail.com');
	INSERT INTO INTERVENTIONS (ETAT, COMMENTAIRE, DATEINTERVENTION, DEFAUT, PERSONNE) VALUES('EN TRAITEMENT', 'Première approche, analyse du défaut', '2015-11-18', 1, 'jerome.fink@hotmail.com');
END;