DROP TABLE Interventions;
DROP TABLE Personnes;
DROP TABLE Defauts;



CREATE TABLE Defauts
(
	IdDefaut INT IDENTITY(1,1) CONSTRAINT PK_DEFAUTS PRIMARY KEY,
	Photo VARBINARY(MAX),
	Description VARCHAR(500),
	Position VARCHAR(40)
);

CREATE TABLE Personnes
(
	Mail VARCHAR(50) CONSTRAINT PK_PERSONNES PRIMARY KEY,
	Password VARCHAR(20),
	Nom VARCHAR(30),
	Prenom VARCHAR(30),
	Type VARCHAR(10) CONSTRAINT CK_TYPE CHECK (Type IN ('CHEF', 'OUVRIER', 'CITOYEN'))
);

CREATE TABLE Interventions
(
	IdIntervention INT IDENTITY(1,1) CONSTRAINT PK_INTERVENTIONS PRIMARY KEY,
	Etat VARCHAR(20) CONSTRAINT CK_ETAT CHECK (Etat IN ('OUVERT', 'EN TRAITEMENT', 'A VALIDER', 'RESOLU')),
	Commentaire VARCHAR(500),
	DateIntervention DATE CONSTRAINT NN_DATEINTERVENTION CHECK (DateIntervention IS NOT NULL),
	Defaut INT CONSTRAINT FK_INTERVENTIONS_DEFAUT REFERENCES DEFAUTS(IdDefaut),
	Personne VARCHAR(50) CONSTRAINT FK_INTERVENTIONS_PERSONNE REFERENCES PERSONNES(Mail),
	CONSTRAINT NN_DEFAUT CHECK (Defaut IS NOT NULL)
);
