DROP TABLE INTERVENTIONS;
DROP TABLE PERSONNES;
DROP TABLE DEFAUTS;



CREATE TABLE DEFAUTS
(
	IdDefaut INT IDENTITY(1,1) CONSTRAINT PK_DEFAUTS PRIMARY KEY,
	Photo VARCHAR(50),
	Description VARCHAR(500),
	Position VARCHAR(40)
);

CREATE TABLE PERSONNES
(
	Mail VARCHAR(50) CONSTRAINT PK_PERSONNES PRIMARY KEY,
	Password VARCHAR(20),
	Nom VARCHAR(30),
	Prenom VARCHAR(30),
	Type VARCHAR(10)
);

CREATE TABLE INTERVENTIONS
(
	IdIntervention INT IDENTITY(1,1) CONSTRAINT PK_INTERVENTIONS PRIMARY KEY,
	Etat VARCHAR(20) CONSTRAINT CK_ETAT CHECK (Etat IN ('OUVERT', 'EN TRAITEMENT', 'A VALIDER', 'RESOLU')),
	Commentaire VARCHAR(500),
	DateIntervention DATE ,
	Defaut INT CONSTRAINT FK_INTERVENTIONS_DEFAUT REFERENCES DEFAUTS(IdDefaut),
	Personne VARCHAR(50) CONSTRAINT FK_INTERVENTIONS_PERSONNE REFERENCES PERSONNES(Mail)
);
