//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SmartCityAndroid.WebServiceSmartCity {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServiceWCFSmartCity", Namespace="http://tempuri.org/")]
    public partial class ServiceWCFSmartCity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDefautsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDefautByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInterventionsByDefautOrderByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastInterventionByDefautOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddInterventionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllOuvriersOperationCompleted;
        
        private System.Threading.SendOrPostCallback sayHelloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceWCFSmartCity() {
            this.Url = "http://localhost:53221/ServiceWCFSmartCity.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnexionCompletedEventHandler ConnexionCompleted;
        
        /// <remarks/>
        public event GetAllDefautsCompletedEventHandler GetAllDefautsCompleted;
        
        /// <remarks/>
        public event GetDefautByIdCompletedEventHandler GetDefautByIdCompleted;
        
        /// <remarks/>
        public event GetInterventionsByDefautOrderByDateCompletedEventHandler GetInterventionsByDefautOrderByDateCompleted;
        
        /// <remarks/>
        public event GetLastInterventionByDefautCompletedEventHandler GetLastInterventionByDefautCompleted;
        
        /// <remarks/>
        public event AddInterventionCompletedEventHandler AddInterventionCompleted;
        
        /// <remarks/>
        public event GetAllOuvriersCompletedEventHandler GetAllOuvriersCompleted;
        
        /// <remarks/>
        public event sayHelloCompletedEventHandler sayHelloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/Connexion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PersonneWCF Connexion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string m, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pwd) {
            object[] results = this.Invoke("Connexion", new object[] {
                        m,
                        pwd});
            return ((PersonneWCF)(results[0]));
        }
        
        /// <remarks/>
        public void ConnexionAsync(string m, string pwd) {
            this.ConnexionAsync(m, pwd, null);
        }
        
        /// <remarks/>
        public void ConnexionAsync(string m, string pwd, object userState) {
            if ((this.ConnexionOperationCompleted == null)) {
                this.ConnexionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnexionOperationCompleted);
            }
            this.InvokeAsync("Connexion", new object[] {
                        m,
                        pwd}, this.ConnexionOperationCompleted, userState);
        }
        
        private void OnConnexionOperationCompleted(object arg) {
            if ((this.ConnexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnexionCompleted(this, new ConnexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/GetAllDefauts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
        public DefautWCF[] GetAllDefauts() {
            object[] results = this.Invoke("GetAllDefauts", new object[0]);
            return ((DefautWCF[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDefautsAsync() {
            this.GetAllDefautsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDefautsAsync(object userState) {
            if ((this.GetAllDefautsOperationCompleted == null)) {
                this.GetAllDefautsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDefautsOperationCompleted);
            }
            this.InvokeAsync("GetAllDefauts", new object[0], this.GetAllDefautsOperationCompleted, userState);
        }
        
        private void OnGetAllDefautsOperationCompleted(object arg) {
            if ((this.GetAllDefautsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDefautsCompleted(this, new GetAllDefautsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/GetDefautById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DefautWCF GetDefautById(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("GetDefautById", new object[] {
                        id,
                        idSpecified});
            return ((DefautWCF)(results[0]));
        }
        
        /// <remarks/>
        public void GetDefautByIdAsync(int id, bool idSpecified) {
            this.GetDefautByIdAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void GetDefautByIdAsync(int id, bool idSpecified, object userState) {
            if ((this.GetDefautByIdOperationCompleted == null)) {
                this.GetDefautByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefautByIdOperationCompleted);
            }
            this.InvokeAsync("GetDefautById", new object[] {
                        id,
                        idSpecified}, this.GetDefautByIdOperationCompleted, userState);
        }
        
        private void OnGetDefautByIdOperationCompleted(object arg) {
            if ((this.GetDefautByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefautByIdCompleted(this, new GetDefautByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
        public InterventionWCF[] GetInterventionsByDefautOrderByDate(int d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified) {
            object[] results = this.Invoke("GetInterventionsByDefautOrderByDate", new object[] {
                        d,
                        dSpecified});
            return ((InterventionWCF[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInterventionsByDefautOrderByDateAsync(int d, bool dSpecified) {
            this.GetInterventionsByDefautOrderByDateAsync(d, dSpecified, null);
        }
        
        /// <remarks/>
        public void GetInterventionsByDefautOrderByDateAsync(int d, bool dSpecified, object userState) {
            if ((this.GetInterventionsByDefautOrderByDateOperationCompleted == null)) {
                this.GetInterventionsByDefautOrderByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterventionsByDefautOrderByDateOperationCompleted);
            }
            this.InvokeAsync("GetInterventionsByDefautOrderByDate", new object[] {
                        d,
                        dSpecified}, this.GetInterventionsByDefautOrderByDateOperationCompleted, userState);
        }
        
        private void OnGetInterventionsByDefautOrderByDateOperationCompleted(object arg) {
            if ((this.GetInterventionsByDefautOrderByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInterventionsByDefautOrderByDateCompleted(this, new GetInterventionsByDefautOrderByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefaut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InterventionWCF GetLastInterventionByDefaut(int d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified) {
            object[] results = this.Invoke("GetLastInterventionByDefaut", new object[] {
                        d,
                        dSpecified});
            return ((InterventionWCF)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastInterventionByDefautAsync(int d, bool dSpecified) {
            this.GetLastInterventionByDefautAsync(d, dSpecified, null);
        }
        
        /// <remarks/>
        public void GetLastInterventionByDefautAsync(int d, bool dSpecified, object userState) {
            if ((this.GetLastInterventionByDefautOperationCompleted == null)) {
                this.GetLastInterventionByDefautOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastInterventionByDefautOperationCompleted);
            }
            this.InvokeAsync("GetLastInterventionByDefaut", new object[] {
                        d,
                        dSpecified}, this.GetLastInterventionByDefautOperationCompleted, userState);
        }
        
        private void OnGetLastInterventionByDefautOperationCompleted(object arg) {
            if ((this.GetLastInterventionByDefautCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastInterventionByDefautCompleted(this, new GetLastInterventionByDefautCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/AddIntervention", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddIntervention([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string e, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string c, System.DateTime d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified, int def, [System.Xml.Serialization.XmlIgnoreAttribute()] bool defSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string p) {
            this.Invoke("AddIntervention", new object[] {
                        e,
                        c,
                        d,
                        dSpecified,
                        def,
                        defSpecified,
                        p});
        }
        
        /// <remarks/>
        public void AddInterventionAsync(string e, string c, System.DateTime d, bool dSpecified, int def, bool defSpecified, string p) {
            this.AddInterventionAsync(e, c, d, dSpecified, def, defSpecified, p, null);
        }
        
        /// <remarks/>
        public void AddInterventionAsync(string e, string c, System.DateTime d, bool dSpecified, int def, bool defSpecified, string p, object userState) {
            if ((this.AddInterventionOperationCompleted == null)) {
                this.AddInterventionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddInterventionOperationCompleted);
            }
            this.InvokeAsync("AddIntervention", new object[] {
                        e,
                        c,
                        d,
                        dSpecified,
                        def,
                        defSpecified,
                        p}, this.AddInterventionOperationCompleted, userState);
        }
        
        private void OnAddInterventionOperationCompleted(object arg) {
            if ((this.AddInterventionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddInterventionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
        public PersonneWCF[] GetAllOuvriers() {
            object[] results = this.Invoke("GetAllOuvriers", new object[0]);
            return ((PersonneWCF[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllOuvriersAsync() {
            this.GetAllOuvriersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllOuvriersAsync(object userState) {
            if ((this.GetAllOuvriersOperationCompleted == null)) {
                this.GetAllOuvriersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOuvriersOperationCompleted);
            }
            this.InvokeAsync("GetAllOuvriers", new object[0], this.GetAllOuvriersOperationCompleted, userState);
        }
        
        private void OnGetAllOuvriersOperationCompleted(object arg) {
            if ((this.GetAllOuvriersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllOuvriersCompleted(this, new GetAllOuvriersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceWCFSmartCity/sayHello", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sayHello() {
            object[] results = this.Invoke("sayHello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sayHelloAsync() {
            this.sayHelloAsync(null);
        }
        
        /// <remarks/>
        public void sayHelloAsync(object userState) {
            if ((this.sayHelloOperationCompleted == null)) {
                this.sayHelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsayHelloOperationCompleted);
            }
            this.InvokeAsync("sayHello", new object[0], this.sayHelloOperationCompleted, userState);
        }
        
        private void OnsayHelloOperationCompleted(object arg) {
            if ((this.sayHelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sayHelloCompleted(this, new sayHelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class PersonneWCF {
        
        private string mailField;
        
        private string nomField;
        
        private string passwordField;
        
        private string prenomField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class InterventionWCF {
        
        private string commentaireField;
        
        private System.DateTime dateInterventionField;
        
        private bool dateInterventionFieldSpecified;
        
        private string etatField;
        
        private int idDefautField;
        
        private bool idDefautFieldSpecified;
        
        private int idInterventionField;
        
        private bool idInterventionFieldSpecified;
        
        private string mailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateIntervention {
            get {
                return this.dateInterventionField;
            }
            set {
                this.dateInterventionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInterventionSpecified {
            get {
                return this.dateInterventionFieldSpecified;
            }
            set {
                this.dateInterventionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Etat {
            get {
                return this.etatField;
            }
            set {
                this.etatField = value;
            }
        }
        
        /// <remarks/>
        public int IdDefaut {
            get {
                return this.idDefautField;
            }
            set {
                this.idDefautField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDefautSpecified {
            get {
                return this.idDefautFieldSpecified;
            }
            set {
                this.idDefautFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdIntervention {
            get {
                return this.idInterventionField;
            }
            set {
                this.idInterventionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdInterventionSpecified {
            get {
                return this.idInterventionFieldSpecified;
            }
            set {
                this.idInterventionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary {
        
        private byte[] bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class DefautWCF {
        
        private System.DateTime dateDefautField;
        
        private bool dateDefautFieldSpecified;
        
        private string descriptionField;
        
        private int idDefautField;
        
        private bool idDefautFieldSpecified;
        
        private Binary photoField;
        
        private string positionField;
        
        /// <remarks/>
        public System.DateTime DateDefaut {
            get {
                return this.dateDefautField;
            }
            set {
                this.dateDefautField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateDefautSpecified {
            get {
                return this.dateDefautFieldSpecified;
            }
            set {
                this.dateDefautFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int IdDefaut {
            get {
                return this.idDefautField;
            }
            set {
                this.idDefautField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDefautSpecified {
            get {
                return this.idDefautFieldSpecified;
            }
            set {
                this.idDefautFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Binary Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConnexionCompletedEventHandler(object sender, ConnexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConnexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonneWCF Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonneWCF)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAllDefautsCompletedEventHandler(object sender, GetAllDefautsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDefautsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDefautsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DefautWCF[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DefautWCF[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetDefautByIdCompletedEventHandler(object sender, GetDefautByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefautByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDefautByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DefautWCF Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DefautWCF)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetInterventionsByDefautOrderByDateCompletedEventHandler(object sender, GetInterventionsByDefautOrderByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInterventionsByDefautOrderByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInterventionsByDefautOrderByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterventionWCF[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterventionWCF[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetLastInterventionByDefautCompletedEventHandler(object sender, GetLastInterventionByDefautCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastInterventionByDefautCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastInterventionByDefautCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InterventionWCF Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InterventionWCF)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AddInterventionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAllOuvriersCompletedEventHandler(object sender, GetAllOuvriersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllOuvriersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllOuvriersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonneWCF[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonneWCF[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void sayHelloCompletedEventHandler(object sender, sayHelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sayHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sayHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591