//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPresentationFoundation.ServiceWCFSmartCityReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCFSmartCityReference.IServiceWCFSmartCity")]
    public interface IServiceWCFSmartCity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/Connexion", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/ConnexionResponse")]
        string Connexion(string m, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/Connexion", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/ConnexionResponse")]
        System.Threading.Tasks.Task<string> ConnexionAsync(string m, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllPersonnes", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllPersonnesResponse")]
        WindowsCommunicationFoundation.PersonneWCF[] GetAllPersonnes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFSmartCity/GetAllPersonnes", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllPersonnesResponse")]
        System.Threading.Tasks.Task<WindowsCommunicationFoundation.PersonneWCF[]> GetAllPersonnesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFSmartCityChannel : WindowsPresentationFoundation.ServiceWCFSmartCityReference.IServiceWCFSmartCity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFSmartCityClient : System.ServiceModel.ClientBase<WindowsPresentationFoundation.ServiceWCFSmartCityReference.IServiceWCFSmartCity>, WindowsPresentationFoundation.ServiceWCFSmartCityReference.IServiceWCFSmartCity {
        
        public ServiceWCFSmartCityClient() {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartCityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFSmartCityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Connexion(string m, string pwd) {
            return base.Channel.Connexion(m, pwd);
        }
        
        public System.Threading.Tasks.Task<string> ConnexionAsync(string m, string pwd) {
            return base.Channel.ConnexionAsync(m, pwd);
        }
        
        public WindowsCommunicationFoundation.PersonneWCF[] GetAllPersonnes() {
            return base.Channel.GetAllPersonnes();
        }
        
        public System.Threading.Tasks.Task<WindowsCommunicationFoundation.PersonneWCF[]> GetAllPersonnesAsync() {
            return base.Channel.GetAllPersonnesAsync();
        }
    }
}
