//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace WindowsCommunicationFoundation
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonneWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class PersonneWCF : object
    {
        
        private string MailField;
        
        private string NomField;
        
        private string PasswordField;
        
        private string PrenomField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom
        {
            get
            {
                return this.PrenomField;
            }
            set
            {
                this.PrenomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefautWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class DefautWCF : object
    {
        
        private System.DateTime DateDefautField;
        
        private string DescriptionField;
        
        private int IdDefautField;
        
        private System.Data.Linq.Binary PhotoField;
        
        private string PositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDefaut
        {
            get
            {
                return this.DateDefautField;
            }
            set
            {
                this.DateDefautField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDefaut
        {
            get
            {
                return this.IdDefautField;
            }
            set
            {
                this.IdDefautField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Linq.Binary Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterventionWCF", Namespace="http://schemas.datacontract.org/2004/07/WindowsCommunicationFoundation")]
    public partial class InterventionWCF : object
    {
        
        private string CommentaireField;
        
        private System.DateTime DateInterventionField;
        
        private string EtatField;
        
        private int IdDefautField;
        
        private int IdInterventionField;
        
        private string MailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentaire
        {
            get
            {
                return this.CommentaireField;
            }
            set
            {
                this.CommentaireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIntervention
        {
            get
            {
                return this.DateInterventionField;
            }
            set
            {
                this.DateInterventionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etat
        {
            get
            {
                return this.EtatField;
            }
            set
            {
                this.EtatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDefaut
        {
            get
            {
                return this.IdDefautField;
            }
            set
            {
                this.IdDefautField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIntervention
        {
            get
            {
                return this.IdInterventionField;
            }
            set
            {
                this.IdInterventionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }
    }
}
namespace System.Data.Linq
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object
    {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceWCFSmartCity")]
public interface IServiceWCFSmartCity
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/Connexion", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/ConnexionResponse")]
    System.IAsyncResult BeginConnexion(string m, string pwd, System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.PersonneWCF EndConnexion(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/GetAllDefauts", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllDefautsResponse")]
    System.IAsyncResult BeginGetAllDefauts(System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.DefautWCF[] EndGetAllDefauts(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/GetDefautById", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetDefautByIdResponse")]
    System.IAsyncResult BeginGetDefautById(int id, System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.DefautWCF EndGetDefautById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDate", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetInterventionsByDefautOrderByDateRespon" +
        "se")]
    System.IAsyncResult BeginGetInterventionsByDefautOrderByDate(int d, System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.InterventionWCF[] EndGetInterventionsByDefautOrderByDate(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefaut", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetLastInterventionByDefautResponse")]
    System.IAsyncResult BeginGetLastInterventionByDefaut(int d, System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.InterventionWCF EndGetLastInterventionByDefaut(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/AddIntervention", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/AddInterventionResponse")]
    System.IAsyncResult BeginAddIntervention(string e, string c, System.DateTime d, int def, string p, System.AsyncCallback callback, object asyncState);
    
    void EndAddIntervention(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriers", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/GetAllOuvriersResponse")]
    System.IAsyncResult BeginGetAllOuvriers(System.AsyncCallback callback, object asyncState);
    
    WindowsCommunicationFoundation.PersonneWCF[] EndGetAllOuvriers(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/OuvrirDefaut", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/OuvrirDefautResponse")]
    System.IAsyncResult BeginOuvrirDefaut(System.Data.Linq.Binary photo, string descr, string pos, string mail, string com, System.AsyncCallback callback, object asyncState);
    
    void EndOuvrirDefaut(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceWCFSmartCity/sayHello", ReplyAction="http://tempuri.org/IServiceWCFSmartCity/sayHelloResponse")]
    System.IAsyncResult BeginsayHello(System.AsyncCallback callback, object asyncState);
    
    string EndsayHello(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceWCFSmartCityChannel : IServiceWCFSmartCity, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ConnexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ConnexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.PersonneWCF Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.PersonneWCF)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAllDefautsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAllDefautsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.DefautWCF[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.DefautWCF[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetDefautByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetDefautByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.DefautWCF Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.DefautWCF)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetInterventionsByDefautOrderByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetInterventionsByDefautOrderByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.InterventionWCF[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.InterventionWCF[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetLastInterventionByDefautCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetLastInterventionByDefautCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.InterventionWCF Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.InterventionWCF)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAllOuvriersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAllOuvriersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WindowsCommunicationFoundation.PersonneWCF[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WindowsCommunicationFoundation.PersonneWCF[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class sayHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public sayHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceWCFSmartCityClient : System.ServiceModel.ClientBase<IServiceWCFSmartCity>, IServiceWCFSmartCity
{
    
    private BeginOperationDelegate onBeginConnexionDelegate;
    
    private EndOperationDelegate onEndConnexionDelegate;
    
    private System.Threading.SendOrPostCallback onConnexionCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAllDefautsDelegate;
    
    private EndOperationDelegate onEndGetAllDefautsDelegate;
    
    private System.Threading.SendOrPostCallback onGetAllDefautsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetDefautByIdDelegate;
    
    private EndOperationDelegate onEndGetDefautByIdDelegate;
    
    private System.Threading.SendOrPostCallback onGetDefautByIdCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetInterventionsByDefautOrderByDateDelegate;
    
    private EndOperationDelegate onEndGetInterventionsByDefautOrderByDateDelegate;
    
    private System.Threading.SendOrPostCallback onGetInterventionsByDefautOrderByDateCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetLastInterventionByDefautDelegate;
    
    private EndOperationDelegate onEndGetLastInterventionByDefautDelegate;
    
    private System.Threading.SendOrPostCallback onGetLastInterventionByDefautCompletedDelegate;
    
    private BeginOperationDelegate onBeginAddInterventionDelegate;
    
    private EndOperationDelegate onEndAddInterventionDelegate;
    
    private System.Threading.SendOrPostCallback onAddInterventionCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAllOuvriersDelegate;
    
    private EndOperationDelegate onEndGetAllOuvriersDelegate;
    
    private System.Threading.SendOrPostCallback onGetAllOuvriersCompletedDelegate;
    
    private BeginOperationDelegate onBeginOuvrirDefautDelegate;
    
    private EndOperationDelegate onEndOuvrirDefautDelegate;
    
    private System.Threading.SendOrPostCallback onOuvrirDefautCompletedDelegate;
    
    private BeginOperationDelegate onBeginsayHelloDelegate;
    
    private EndOperationDelegate onEndsayHelloDelegate;
    
    private System.Threading.SendOrPostCallback onsayHelloCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public ServiceWCFSmartCityClient()
    {
    }
    
    public ServiceWCFSmartCityClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceWCFSmartCityClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceWCFSmartCityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceWCFSmartCityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<ConnexionCompletedEventArgs> ConnexionCompleted;
    
    public event System.EventHandler<GetAllDefautsCompletedEventArgs> GetAllDefautsCompleted;
    
    public event System.EventHandler<GetDefautByIdCompletedEventArgs> GetDefautByIdCompleted;
    
    public event System.EventHandler<GetInterventionsByDefautOrderByDateCompletedEventArgs> GetInterventionsByDefautOrderByDateCompleted;
    
    public event System.EventHandler<GetLastInterventionByDefautCompletedEventArgs> GetLastInterventionByDefautCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddInterventionCompleted;
    
    public event System.EventHandler<GetAllOuvriersCompletedEventArgs> GetAllOuvriersCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OuvrirDefautCompleted;
    
    public event System.EventHandler<sayHelloCompletedEventArgs> sayHelloCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginConnexion(string m, string pwd, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginConnexion(m, pwd, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.PersonneWCF IServiceWCFSmartCity.EndConnexion(System.IAsyncResult result)
    {
        return base.Channel.EndConnexion(result);
    }
    
    private System.IAsyncResult OnBeginConnexion(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string m = ((string)(inValues[0]));
        string pwd = ((string)(inValues[1]));
        return ((IServiceWCFSmartCity)(this)).BeginConnexion(m, pwd, callback, asyncState);
    }
    
    private object[] OnEndConnexion(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.PersonneWCF retVal = ((IServiceWCFSmartCity)(this)).EndConnexion(result);
        return new object[] {
                retVal};
    }
    
    private void OnConnexionCompleted(object state)
    {
        if ((this.ConnexionCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ConnexionCompleted(this, new ConnexionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ConnexionAsync(string m, string pwd)
    {
        this.ConnexionAsync(m, pwd, null);
    }
    
    public void ConnexionAsync(string m, string pwd, object userState)
    {
        if ((this.onBeginConnexionDelegate == null))
        {
            this.onBeginConnexionDelegate = new BeginOperationDelegate(this.OnBeginConnexion);
        }
        if ((this.onEndConnexionDelegate == null))
        {
            this.onEndConnexionDelegate = new EndOperationDelegate(this.OnEndConnexion);
        }
        if ((this.onConnexionCompletedDelegate == null))
        {
            this.onConnexionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConnexionCompleted);
        }
        base.InvokeAsync(this.onBeginConnexionDelegate, new object[] {
                    m,
                    pwd}, this.onEndConnexionDelegate, this.onConnexionCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginGetAllDefauts(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAllDefauts(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.DefautWCF[] IServiceWCFSmartCity.EndGetAllDefauts(System.IAsyncResult result)
    {
        return base.Channel.EndGetAllDefauts(result);
    }
    
    private System.IAsyncResult OnBeginGetAllDefauts(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IServiceWCFSmartCity)(this)).BeginGetAllDefauts(callback, asyncState);
    }
    
    private object[] OnEndGetAllDefauts(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.DefautWCF[] retVal = ((IServiceWCFSmartCity)(this)).EndGetAllDefauts(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAllDefautsCompleted(object state)
    {
        if ((this.GetAllDefautsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAllDefautsCompleted(this, new GetAllDefautsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAllDefautsAsync()
    {
        this.GetAllDefautsAsync(null);
    }
    
    public void GetAllDefautsAsync(object userState)
    {
        if ((this.onBeginGetAllDefautsDelegate == null))
        {
            this.onBeginGetAllDefautsDelegate = new BeginOperationDelegate(this.OnBeginGetAllDefauts);
        }
        if ((this.onEndGetAllDefautsDelegate == null))
        {
            this.onEndGetAllDefautsDelegate = new EndOperationDelegate(this.OnEndGetAllDefauts);
        }
        if ((this.onGetAllDefautsCompletedDelegate == null))
        {
            this.onGetAllDefautsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllDefautsCompleted);
        }
        base.InvokeAsync(this.onBeginGetAllDefautsDelegate, null, this.onEndGetAllDefautsDelegate, this.onGetAllDefautsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginGetDefautById(int id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDefautById(id, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.DefautWCF IServiceWCFSmartCity.EndGetDefautById(System.IAsyncResult result)
    {
        return base.Channel.EndGetDefautById(result);
    }
    
    private System.IAsyncResult OnBeginGetDefautById(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int id = ((int)(inValues[0]));
        return ((IServiceWCFSmartCity)(this)).BeginGetDefautById(id, callback, asyncState);
    }
    
    private object[] OnEndGetDefautById(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.DefautWCF retVal = ((IServiceWCFSmartCity)(this)).EndGetDefautById(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetDefautByIdCompleted(object state)
    {
        if ((this.GetDefautByIdCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetDefautByIdCompleted(this, new GetDefautByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetDefautByIdAsync(int id)
    {
        this.GetDefautByIdAsync(id, null);
    }
    
    public void GetDefautByIdAsync(int id, object userState)
    {
        if ((this.onBeginGetDefautByIdDelegate == null))
        {
            this.onBeginGetDefautByIdDelegate = new BeginOperationDelegate(this.OnBeginGetDefautById);
        }
        if ((this.onEndGetDefautByIdDelegate == null))
        {
            this.onEndGetDefautByIdDelegate = new EndOperationDelegate(this.OnEndGetDefautById);
        }
        if ((this.onGetDefautByIdCompletedDelegate == null))
        {
            this.onGetDefautByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDefautByIdCompleted);
        }
        base.InvokeAsync(this.onBeginGetDefautByIdDelegate, new object[] {
                    id}, this.onEndGetDefautByIdDelegate, this.onGetDefautByIdCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginGetInterventionsByDefautOrderByDate(int d, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetInterventionsByDefautOrderByDate(d, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.InterventionWCF[] IServiceWCFSmartCity.EndGetInterventionsByDefautOrderByDate(System.IAsyncResult result)
    {
        return base.Channel.EndGetInterventionsByDefautOrderByDate(result);
    }
    
    private System.IAsyncResult OnBeginGetInterventionsByDefautOrderByDate(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int d = ((int)(inValues[0]));
        return ((IServiceWCFSmartCity)(this)).BeginGetInterventionsByDefautOrderByDate(d, callback, asyncState);
    }
    
    private object[] OnEndGetInterventionsByDefautOrderByDate(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.InterventionWCF[] retVal = ((IServiceWCFSmartCity)(this)).EndGetInterventionsByDefautOrderByDate(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetInterventionsByDefautOrderByDateCompleted(object state)
    {
        if ((this.GetInterventionsByDefautOrderByDateCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetInterventionsByDefautOrderByDateCompleted(this, new GetInterventionsByDefautOrderByDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetInterventionsByDefautOrderByDateAsync(int d)
    {
        this.GetInterventionsByDefautOrderByDateAsync(d, null);
    }
    
    public void GetInterventionsByDefautOrderByDateAsync(int d, object userState)
    {
        if ((this.onBeginGetInterventionsByDefautOrderByDateDelegate == null))
        {
            this.onBeginGetInterventionsByDefautOrderByDateDelegate = new BeginOperationDelegate(this.OnBeginGetInterventionsByDefautOrderByDate);
        }
        if ((this.onEndGetInterventionsByDefautOrderByDateDelegate == null))
        {
            this.onEndGetInterventionsByDefautOrderByDateDelegate = new EndOperationDelegate(this.OnEndGetInterventionsByDefautOrderByDate);
        }
        if ((this.onGetInterventionsByDefautOrderByDateCompletedDelegate == null))
        {
            this.onGetInterventionsByDefautOrderByDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInterventionsByDefautOrderByDateCompleted);
        }
        base.InvokeAsync(this.onBeginGetInterventionsByDefautOrderByDateDelegate, new object[] {
                    d}, this.onEndGetInterventionsByDefautOrderByDateDelegate, this.onGetInterventionsByDefautOrderByDateCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginGetLastInterventionByDefaut(int d, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetLastInterventionByDefaut(d, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.InterventionWCF IServiceWCFSmartCity.EndGetLastInterventionByDefaut(System.IAsyncResult result)
    {
        return base.Channel.EndGetLastInterventionByDefaut(result);
    }
    
    private System.IAsyncResult OnBeginGetLastInterventionByDefaut(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int d = ((int)(inValues[0]));
        return ((IServiceWCFSmartCity)(this)).BeginGetLastInterventionByDefaut(d, callback, asyncState);
    }
    
    private object[] OnEndGetLastInterventionByDefaut(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.InterventionWCF retVal = ((IServiceWCFSmartCity)(this)).EndGetLastInterventionByDefaut(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetLastInterventionByDefautCompleted(object state)
    {
        if ((this.GetLastInterventionByDefautCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetLastInterventionByDefautCompleted(this, new GetLastInterventionByDefautCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetLastInterventionByDefautAsync(int d)
    {
        this.GetLastInterventionByDefautAsync(d, null);
    }
    
    public void GetLastInterventionByDefautAsync(int d, object userState)
    {
        if ((this.onBeginGetLastInterventionByDefautDelegate == null))
        {
            this.onBeginGetLastInterventionByDefautDelegate = new BeginOperationDelegate(this.OnBeginGetLastInterventionByDefaut);
        }
        if ((this.onEndGetLastInterventionByDefautDelegate == null))
        {
            this.onEndGetLastInterventionByDefautDelegate = new EndOperationDelegate(this.OnEndGetLastInterventionByDefaut);
        }
        if ((this.onGetLastInterventionByDefautCompletedDelegate == null))
        {
            this.onGetLastInterventionByDefautCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastInterventionByDefautCompleted);
        }
        base.InvokeAsync(this.onBeginGetLastInterventionByDefautDelegate, new object[] {
                    d}, this.onEndGetLastInterventionByDefautDelegate, this.onGetLastInterventionByDefautCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginAddIntervention(string e, string c, System.DateTime d, int def, string p, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAddIntervention(e, c, d, def, p, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IServiceWCFSmartCity.EndAddIntervention(System.IAsyncResult result)
    {
        base.Channel.EndAddIntervention(result);
    }
    
    private System.IAsyncResult OnBeginAddIntervention(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string e = ((string)(inValues[0]));
        string c = ((string)(inValues[1]));
        System.DateTime d = ((System.DateTime)(inValues[2]));
        int def = ((int)(inValues[3]));
        string p = ((string)(inValues[4]));
        return ((IServiceWCFSmartCity)(this)).BeginAddIntervention(e, c, d, def, p, callback, asyncState);
    }
    
    private object[] OnEndAddIntervention(System.IAsyncResult result)
    {
        ((IServiceWCFSmartCity)(this)).EndAddIntervention(result);
        return null;
    }
    
    private void OnAddInterventionCompleted(object state)
    {
        if ((this.AddInterventionCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AddInterventionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AddInterventionAsync(string e, string c, System.DateTime d, int def, string p)
    {
        this.AddInterventionAsync(e, c, d, def, p, null);
    }
    
    public void AddInterventionAsync(string e, string c, System.DateTime d, int def, string p, object userState)
    {
        if ((this.onBeginAddInterventionDelegate == null))
        {
            this.onBeginAddInterventionDelegate = new BeginOperationDelegate(this.OnBeginAddIntervention);
        }
        if ((this.onEndAddInterventionDelegate == null))
        {
            this.onEndAddInterventionDelegate = new EndOperationDelegate(this.OnEndAddIntervention);
        }
        if ((this.onAddInterventionCompletedDelegate == null))
        {
            this.onAddInterventionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddInterventionCompleted);
        }
        base.InvokeAsync(this.onBeginAddInterventionDelegate, new object[] {
                    e,
                    c,
                    d,
                    def,
                    p}, this.onEndAddInterventionDelegate, this.onAddInterventionCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginGetAllOuvriers(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAllOuvriers(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WindowsCommunicationFoundation.PersonneWCF[] IServiceWCFSmartCity.EndGetAllOuvriers(System.IAsyncResult result)
    {
        return base.Channel.EndGetAllOuvriers(result);
    }
    
    private System.IAsyncResult OnBeginGetAllOuvriers(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IServiceWCFSmartCity)(this)).BeginGetAllOuvriers(callback, asyncState);
    }
    
    private object[] OnEndGetAllOuvriers(System.IAsyncResult result)
    {
        WindowsCommunicationFoundation.PersonneWCF[] retVal = ((IServiceWCFSmartCity)(this)).EndGetAllOuvriers(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAllOuvriersCompleted(object state)
    {
        if ((this.GetAllOuvriersCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAllOuvriersCompleted(this, new GetAllOuvriersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAllOuvriersAsync()
    {
        this.GetAllOuvriersAsync(null);
    }
    
    public void GetAllOuvriersAsync(object userState)
    {
        if ((this.onBeginGetAllOuvriersDelegate == null))
        {
            this.onBeginGetAllOuvriersDelegate = new BeginOperationDelegate(this.OnBeginGetAllOuvriers);
        }
        if ((this.onEndGetAllOuvriersDelegate == null))
        {
            this.onEndGetAllOuvriersDelegate = new EndOperationDelegate(this.OnEndGetAllOuvriers);
        }
        if ((this.onGetAllOuvriersCompletedDelegate == null))
        {
            this.onGetAllOuvriersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllOuvriersCompleted);
        }
        base.InvokeAsync(this.onBeginGetAllOuvriersDelegate, null, this.onEndGetAllOuvriersDelegate, this.onGetAllOuvriersCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginOuvrirDefaut(System.Data.Linq.Binary photo, string descr, string pos, string mail, string com, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginOuvrirDefaut(photo, descr, pos, mail, com, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IServiceWCFSmartCity.EndOuvrirDefaut(System.IAsyncResult result)
    {
        base.Channel.EndOuvrirDefaut(result);
    }
    
    private System.IAsyncResult OnBeginOuvrirDefaut(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        System.Data.Linq.Binary photo = ((System.Data.Linq.Binary)(inValues[0]));
        string descr = ((string)(inValues[1]));
        string pos = ((string)(inValues[2]));
        string mail = ((string)(inValues[3]));
        string com = ((string)(inValues[4]));
        return ((IServiceWCFSmartCity)(this)).BeginOuvrirDefaut(photo, descr, pos, mail, com, callback, asyncState);
    }
    
    private object[] OnEndOuvrirDefaut(System.IAsyncResult result)
    {
        ((IServiceWCFSmartCity)(this)).EndOuvrirDefaut(result);
        return null;
    }
    
    private void OnOuvrirDefautCompleted(object state)
    {
        if ((this.OuvrirDefautCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OuvrirDefautCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OuvrirDefautAsync(System.Data.Linq.Binary photo, string descr, string pos, string mail, string com)
    {
        this.OuvrirDefautAsync(photo, descr, pos, mail, com, null);
    }
    
    public void OuvrirDefautAsync(System.Data.Linq.Binary photo, string descr, string pos, string mail, string com, object userState)
    {
        if ((this.onBeginOuvrirDefautDelegate == null))
        {
            this.onBeginOuvrirDefautDelegate = new BeginOperationDelegate(this.OnBeginOuvrirDefaut);
        }
        if ((this.onEndOuvrirDefautDelegate == null))
        {
            this.onEndOuvrirDefautDelegate = new EndOperationDelegate(this.OnEndOuvrirDefaut);
        }
        if ((this.onOuvrirDefautCompletedDelegate == null))
        {
            this.onOuvrirDefautCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOuvrirDefautCompleted);
        }
        base.InvokeAsync(this.onBeginOuvrirDefautDelegate, new object[] {
                    photo,
                    descr,
                    pos,
                    mail,
                    com}, this.onEndOuvrirDefautDelegate, this.onOuvrirDefautCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceWCFSmartCity.BeginsayHello(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginsayHello(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IServiceWCFSmartCity.EndsayHello(System.IAsyncResult result)
    {
        return base.Channel.EndsayHello(result);
    }
    
    private System.IAsyncResult OnBeginsayHello(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IServiceWCFSmartCity)(this)).BeginsayHello(callback, asyncState);
    }
    
    private object[] OnEndsayHello(System.IAsyncResult result)
    {
        string retVal = ((IServiceWCFSmartCity)(this)).EndsayHello(result);
        return new object[] {
                retVal};
    }
    
    private void OnsayHelloCompleted(object state)
    {
        if ((this.sayHelloCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.sayHelloCompleted(this, new sayHelloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void sayHelloAsync()
    {
        this.sayHelloAsync(null);
    }
    
    public void sayHelloAsync(object userState)
    {
        if ((this.onBeginsayHelloDelegate == null))
        {
            this.onBeginsayHelloDelegate = new BeginOperationDelegate(this.OnBeginsayHello);
        }
        if ((this.onEndsayHelloDelegate == null))
        {
            this.onEndsayHelloDelegate = new EndOperationDelegate(this.OnEndsayHello);
        }
        if ((this.onsayHelloCompletedDelegate == null))
        {
            this.onsayHelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsayHelloCompleted);
        }
        base.InvokeAsync(this.onBeginsayHelloDelegate, null, this.onEndsayHelloDelegate, this.onsayHelloCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IServiceWCFSmartCity CreateChannel()
    {
        return new ServiceWCFSmartCityClientChannel(this);
    }
    
    private class ServiceWCFSmartCityClientChannel : ChannelBase<IServiceWCFSmartCity>, IServiceWCFSmartCity
    {
        
        public ServiceWCFSmartCityClientChannel(System.ServiceModel.ClientBase<IServiceWCFSmartCity> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginConnexion(string m, string pwd, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = m;
            _args[1] = pwd;
            System.IAsyncResult _result = base.BeginInvoke("Connexion", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.PersonneWCF EndConnexion(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.PersonneWCF _result = ((WindowsCommunicationFoundation.PersonneWCF)(base.EndInvoke("Connexion", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetAllDefauts(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetAllDefauts", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.DefautWCF[] EndGetAllDefauts(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.DefautWCF[] _result = ((WindowsCommunicationFoundation.DefautWCF[])(base.EndInvoke("GetAllDefauts", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetDefautById(int id, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = id;
            System.IAsyncResult _result = base.BeginInvoke("GetDefautById", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.DefautWCF EndGetDefautById(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.DefautWCF _result = ((WindowsCommunicationFoundation.DefautWCF)(base.EndInvoke("GetDefautById", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetInterventionsByDefautOrderByDate(int d, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = d;
            System.IAsyncResult _result = base.BeginInvoke("GetInterventionsByDefautOrderByDate", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.InterventionWCF[] EndGetInterventionsByDefautOrderByDate(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.InterventionWCF[] _result = ((WindowsCommunicationFoundation.InterventionWCF[])(base.EndInvoke("GetInterventionsByDefautOrderByDate", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetLastInterventionByDefaut(int d, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = d;
            System.IAsyncResult _result = base.BeginInvoke("GetLastInterventionByDefaut", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.InterventionWCF EndGetLastInterventionByDefaut(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.InterventionWCF _result = ((WindowsCommunicationFoundation.InterventionWCF)(base.EndInvoke("GetLastInterventionByDefaut", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginAddIntervention(string e, string c, System.DateTime d, int def, string p, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[5];
            _args[0] = e;
            _args[1] = c;
            _args[2] = d;
            _args[3] = def;
            _args[4] = p;
            System.IAsyncResult _result = base.BeginInvoke("AddIntervention", _args, callback, asyncState);
            return _result;
        }
        
        public void EndAddIntervention(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("AddIntervention", _args, result);
        }
        
        public System.IAsyncResult BeginGetAllOuvriers(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetAllOuvriers", _args, callback, asyncState);
            return _result;
        }
        
        public WindowsCommunicationFoundation.PersonneWCF[] EndGetAllOuvriers(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WindowsCommunicationFoundation.PersonneWCF[] _result = ((WindowsCommunicationFoundation.PersonneWCF[])(base.EndInvoke("GetAllOuvriers", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginOuvrirDefaut(System.Data.Linq.Binary photo, string descr, string pos, string mail, string com, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[5];
            _args[0] = photo;
            _args[1] = descr;
            _args[2] = pos;
            _args[3] = mail;
            _args[4] = com;
            System.IAsyncResult _result = base.BeginInvoke("OuvrirDefaut", _args, callback, asyncState);
            return _result;
        }
        
        public void EndOuvrirDefaut(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("OuvrirDefaut", _args, result);
        }
        
        public System.IAsyncResult BeginsayHello(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("sayHello", _args, callback, asyncState);
            return _result;
        }
        
        public string EndsayHello(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("sayHello", _args, result)));
            return _result;
        }
    }
}
